## GitHub Actions - Build app on Pages and Test code

# 1. Build une app front-end JS qui crée un artifact et publie l’app sur GitHub Pages.
# 2. Créer une action qui teste le code du dépot lorsque du code est ajouté ou qu’une pull request est créé sur la branche main.


name: Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 18.x
      uses: actions/setup-node@v2
      with:
        node-version: 18.x

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build



