## Créer une action qui teste le code du dépot lorsque du code est ajouté ou qu’une pull request est créé sur la branche main.

name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Code
          uses: actions/checkout@v2

        - name: Use Node.js 18.x
          uses: actions/setup-node@v2
          with:
            node-version: 18.x

        - name: Install dependencies
          run: npm install

        - name: Test
          run: npm run test